server:
  port: 8088
    #servlet:
  #context-path: /demo

spring:
  mvc:
    view:
      prefix: /
      suffix: .html


# 待转换为yml树形结构
# Enable template caching.
#spring.freemarker.cache=true
# Check that the templates location exists.
#spring.freemarker.check-template-location=true
# Content-Type value.
#spring.freemarker.servlet.content-type=text/html
# Enable MVC Thymeleaf view resolution.
#spring.freemarker.enabled=true
# Template encoding.
#spring.freemarker.encoding=UTF-8
# Comma-separated list of view names that should be excluded from resolution.
#spring.freemarker.excluded-view-names=
# Template mode to be applied to templates. See also StandardTemplateModeHandlers.
#spring.freemarker.mode=HTML5
# Prefix that gets prepended to view names when building a URL.
#spring.freemarker.prefix=classpath:/templates/
# Suffix that gets appended to view names when building a URL.
#spring.freemarker.suffix=.html
logging:
  config: classpath:log4j2-spring.xml
  #file: log/bootTest.log
